src/main/scala/viper/gobra/frontend/info/implementation/typing/StmtTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/TypeTyping.scala
src/test/resources/regressions/issues/000043.gobra

Add type system level check for invalid recursive type definitions as described in issue #43

Fix issue 43

---

src/main/scala/viper/gobra/reporting/DefaultErrorBackTranslator.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/test/resources/regressions/issues/000109.gobra

Fixes #109 as `vprerr.CallFailed` was not translated

Translation of Additional Silver Errors

---

src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMemberTyping.scala
src/test/resources/regressions/examples/tour/Test4.gobra
src/test/resources/regressions/features/no_semicolons/examples/tour/Test4.gobra
src/test/resources/regressions/features/no_semicolons/ternary_operator/ternary-operator3.gobra
src/test/resources/regressions/features/ternary_operator/ternary-operator3.gobra
src/test/resources/regressions/issues/000114-1.gobra
src/test/resources/regressions/issues/000114-2.gobra

Adds a check for pure methods and functions that the postconditions are pure
Fixes #114

Restrictions for Pure Members

---

src/main/scala/viper/gobra/translator/encodings/arrays/ArrayEncoding.scala
src/test/resources/regressions/issues/000121.gobra

A fix for issue #121. I added the length information to array default values. Furhermore, equalitiy of zero-sized arrays is now more precise.

Fixes Issue #121

---

src/test/resources/regressions/issues/000015.gobra

Adds a test for issue 15, which was fixed in PR #117 .

Adds test for issue #15

---

src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/UnderlyingType.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/MemberTyping.scala
src/test/resources/regressions/issues/000034-1.gobra
src/test/resources/regressions/issues/000034-2.gobra

Fix issue 34

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000155.gobra

Fix issue 155

---

src/main/scala/viper/gobra/frontend/info/implementation/property/Assignability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/UnderlyingType.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/test/resources/regressions/issues/000157-1.gobra
src/test/resources/regressions/issues/000157-2.gobra
src/test/resources/regressions/issues/000157-3.gobra
src/test/resources/regressions/issues/000157-4.gobra

Fixes issue #157 and a couple of other bugs type system bugs described in files `000157-3.gobra` and `000157-4.gobra`

Fix issue 157

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/test/resources/regressions/features/quantifiers/exists-trigger-fail1.gobra
src/test/resources/regressions/features/quantifiers/exists-trigger-fail2.gobra
src/test/resources/regressions/features/quantifiers/exists-trigger-fail5.gobra
src/test/resources/regressions/features/quantifiers/forall-trigger-fail1.gobra
src/test/resources/regressions/features/quantifiers/forall-trigger-fail2.gobra
src/test/resources/regressions/features/quantifiers/forall-trigger-fail5.gobra
src/test/resources/regressions/features/quantifiers/forall-trigger-fail6.gobra
src/test/resources/regressions/features/quantifiers/quantperms-fail4.gobra
src/test/resources/regressions/issues/000177.gobra

Temporary workaround to issue #177, as discussed in today's Gobra meeting. The test introduced in this PR is the exact same one that Martin provided in the issue description.

Workaround restricted triggers

---

src/main/scala/viper/gobra/translator/implementations/translator/PureMethodsImpl.scala
src/test/resources/regressions/issues/000180.gobra

Fixes encoding of result variable in postconditions of pure methods

---

src/main/scala/viper/gobra/translator/Names.scala
src/test/resources/regressions/issues/000182.gobra

Type sanitization for Viper types with multiple type parameters

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/TypeEncoding.scala
src/main/scala/viper/gobra/translator/encodings/combinators/FinalTypeEncoding.scala
src/main/scala/viper/gobra/translator/encodings/combinators/TypeEncodingCombiner.scala
src/main/scala/viper/gobra/translator/encodings/interfaces/InterfaceEncoding.scala
src/main/scala/viper/gobra/translator/encodings/interfaces/TypeComponentImpl.scala
src/main/scala/viper/gobra/translator/implementations/translator/ExpressionsImpl.scala
src/test/resources/regressions/examples/example-2-2.gobra
src/test/resources/regressions/examples/visitor_pattern.gobra

added visitor pattern example for paper

---

src/test/resources/regressions/examples/example-2-1.gobra

Small addition to example-2-1

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000236.gobra

Fix issue 236

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/translator/encodings/interfaces/TypeComponentImpl.scala
src/test/resources/regressions/features/interfaces/boxAndUnbox1.gobra
src/test/resources/regressions/features/interfaces/safeTypeAssertion1.gobra
src/test/resources/regressions/issues/000134.gobra

Fixes how fields are desugared.

Fix issue 134

---

src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/ast/frontend/PrettyPrinter.scala
src/main/scala/viper/gobra/frontend/info/base/SymbolTable.scala
src/main/scala/viper/gobra/frontend/info/base/Type.scala
src/test/resources/regressions/issues/000249.gobra

Adds toString methods to (parse tree) types and symbol table entries.

Fix issue 249

---

src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/ast/frontend/PrettyPrinter.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/info/base/Type.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Addressability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Assignability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Comparability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/TypeIdentity.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/TypeMerging.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/UnderlyingType.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/MiscTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostTypeTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostWellDef.scala
src/test/resources/regressions/examples/impl_errors/parallel_sum.gobra
src/test/resources/regressions/examples/parallel_sum.gobra
src/test/resources/regressions/examples/spec_errors/parallel_sum.gobra

I added a ghost slice and adapted the exsting files accordingly.
I created an additional branch because I expected that I will have to adapt test cases, which fortunately was not the case.

No allocation in ghost code

---

src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/info/ExternalTypeInfo.scala
src/main/scala/viper/gobra/frontend/info/TypeInfo.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Assignability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/BaseProperty.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Comparability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Implements.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/TypeIdentity.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/AdvancedMemberSet.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMemberTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMiscTyping.scala
src/test/resources/regressions/examples/example-2-2.gobra
src/test/resources/regressions/examples/impl_errors/visitor_pattern.gobra

This is not yet completely done, but I would want to merge it in to avoid a PR that is too big later on.
I added a lot of consistency checks. Furthermore, I added that types can be parsed as part of an equality. Lastly, I improved error messages.

Interface more checks

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMemberTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMiscTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostStmtTyping.scala
src/main/scala/viper/gobra/reporting/DefaultErrorBackTranslator.scala
src/main/scala/viper/gobra/reporting/Source.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/test/resources/regressions/examples/binary_search_tree.gobra
src/test/resources/regressions/examples/impl_errors/binary_search_tree.gobra
src/test/resources/regressions/examples/spec_errors/binary_search_tree.gobra
src/test/resources/regressions/examples/switch.gobra
src/test/resources/regressions/features/import/fpredicate_import/main.gobra
src/test/resources/regressions/features/import/ghost_member_import/main.gobra
src/test/resources/regressions/features/import/method_import/main.gobra
src/test/resources/regressions/features/import/method_import/main2.gobra
src/test/resources/regressions/features/import/mpredicate_import/main.gobra
src/test/resources/regressions/features/import/namespace_import/main.gobra
src/test/resources/regressions/features/import/unqualified_import/functions/main3.gobra
src/test/resources/regressions/features/import/unqualified_import/methods/main.gobra
src/test/resources/regressions/features/predicates/predicates_ill_formed1.gobra
src/test/resources/regressions/features/strings/strings0.gobra
src/test/resources/regressions/features/stubs/stubs0.gobra
src/test/resources/regressions/issues/000033-1.gobra
src/test/resources/regressions/issues/000033-2.gobra
src/test/resources/regressions/issues/000033-3.gobra
src/test/resources/regressions/issues/000033-4.gobra
src/test/resources/regressions/issues/000033-5.gobra
src/test/resources/regressions/issues/000035.gobra

I made the error backtranslation more robust and fixed a bug concerning assertions. Before, the body of an assertion could be impure, which is forbidden now.

More robust error backtranslation.

---

src/main/scala/viper/gobra/reporting/DefaultErrorBackTranslator.scala
src/main/scala/viper/gobra/reporting/Source.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala
src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/main/scala/viper/gobra/translator/util/ViperWriter.scala

Improves error messages for channels.

improved error messages

---

src/main/scala/viper/gobra/frontend/info/implementation/property/Assignability.scala
src/test/resources/regressions/issues/000282.gobra

Add fix to allow variadic arguments to be assigned to slices.

Variadic assign

---

README.md

Add link to Zulip in the README

Add link to Zulip

---

src/main/scala/viper/gobra/frontend/Parser.scala
src/test/resources/regressions/issues/000299.gobra

The "pure" annotation can now be at several positions in the specification.

Fixes #299

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMemberTyping.scala
src/test/resources/regressions/issues/000308.gobra

Fix issue 308

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/BaseTyping.scala
src/test/resources/regressions/issues/000318.gobra

Fixes issue #318 by avoiding the checks for well definedness which occur in an interface definition.

Fix issue #318

---

src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala
src/test/resources/regressions/features/strings/string-slice-fail0.gobra
src/test/resources/regressions/features/strings/string-slice-fail1.gobra
src/test/resources/regressions/features/strings/string-slice-simple0.gobra

Adds support for slicing strings.

Add string slicing

---

src/main/scala/viper/gobra/frontend/info/implementation/property/ConstantEvaluation.scala
src/test/resources/regressions/issues/000316.gobra

Fix issue #316 which was caused by using an incorrect context to type an expression.

Fix issue 316

---

.dockerignore
.github/workflows/docker-push.yml
workflow-container/Dockerfile

Added a docker image, containing gobra, z3 and boogie to be used by the [Gobra GitHub Action](https://github.com/jogasser/gobra-action) and added a workflow publishing to the GitHub package repository

Add docker image to package repository

---

src/main/resources/stubs/time/time.gobra
src/main/resources/stubs/time/zoneinfo.gobra

Changes:
- adds termination to the time package

added termination to time package

---

.github/workflows/test.yml

Fix for Issue 363

---

src/main/resources/stubs/bytes/bytes.gobra
src/main/resources/stubs/time/sleep.gobra
src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala

As Is:
- no support for the bytes package
- no support for time.Sleep method
To Be:
- added bytes package
- added time.Sleep method

added bytes package stub and added support for time.sleep method

---

src/main/resources/stubs/bytes/bytes.gobra
src/main/resources/stubs/time/sleep.gobra
src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala

This PR adds the changes from PR #382 to the main branch. Lino merged it in the branch `verified-scion-preview-without-selective` which will soon be deprecated.

Add Lino's stubs to master

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/ExternalTypeInfo.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Implements.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/NameResolution.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMemberTyping.scala
src/test/resources/regressions/features/interfaces/ghostMembers.gobra
src/test/resources/regressions/features/interfaces/proofGenForImport.gobra
src/test/resources/regressions/features/interfaces/proofGenForImportPkg/pkg.gobra

As discussed and as described in `proofGenForImport.gobra` and `proofGenForImportPkg/pkg.gobra`
Depends on #392

Implementation Proof Generation for Imported Subtyping Relations

---

src/main/scala/viper/gobra/frontend/Parser.scala

Currently, the parser cache caches parse ASTs. However, it does not take the `specOnly` flag into account, meaning that there could be the situation of parsing a package first with `specOnly` set to true (because it's imported in a different package) and later parsing the same package with `specOnly` turned off. In this case, the cache would incorrectly return an AST with abstract functions & methods.
This PR fixes the cache to keep the ASTs for a given file and different  `specOnly` flags separate by including the `specOnly` flag in the key used for cache lookups.

Parser Cache Fix

---

src/main/scala/viper/gobra/frontend/Parser.scala

Parser Cache Fix (Take 2)

---

src/main/scala/viper/gobra/util/ViperChopper.scala

There was a bug in the smallestCut method causing the result to not be the smallest cut. I fixed this.
Furthermore, I changed the default parameter of the penaltiy function.

fixed a bug in the smallestCut method

---

src/main/scala/viper/gobra/util/ViperChopper.scala
src/test/resources/regressions/issues/000411.gobra

Fixes #411. The problem was that dfs stopped when it found an already visited node.

Fixes issue #411

---

src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/translator/encodings/interfaces/InterfaceEncoding.scala
src/main/scala/viper/gobra/translator/encodings/interfaces/TypeComponentImpl.scala

This PR addresses the following two sources of inconsistency:
- interface implementations are not ordered and thus postconditions or if statements appear in different orders (fix: use `SortedSet` instead of `Set`)
- Generation of functions in the `Types` domain happens in non-deterministic order. Thus, the tag assigned to each type might change across encodings (fix: introduction of a unique `tag` domain function)
@jogasser This PR should address the cache misses reported by you

Further Improve Consistency of Encoding

---

GobraChopper.conf
src/main/scala/viper/gobra/frontend/Source.scala
src/main/scala/viper/gobra/util/ChopperUtil.scala
src/main/scala/viper/gobra/util/ViperChopper.scala

- added more precise handling of method without body
- restricted selection of isolated nodes to nodes of the files provided with -i

Precise Handling of Method without Body and more restricted isolated nodes.

---

src/main/resources/stubs/strconv/atoi.gobra

Strengthens the specification of ParseUint

strengthen specification for ParseUint

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/Source.scala
src/main/scala/viper/gobra/reporting/DefaultErrorBackTranslator.scala
src/main/scala/viper/gobra/reporting/Source.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/main/scala/viper/gobra/translator/Names.scala
src/main/scala/viper/gobra/translator/encodings/interfaces/InterfaceEncoding.scala
src/test/resources/regressions/examples/evaluation/impl_errors/visitor_pattern.gobra
src/test/resources/regressions/examples/evaluation/spec_errors/visitor_pattern.gobra
src/test/resources/regressions/examples/evaluation/visitor_pattern.gobra
src/test/resources/regressions/features/errors/error-simple2.gobra
src/test/resources/regressions/features/errors/error-simple3.gobra
src/test/resources/regressions/features/interfaces/predicateWithInterfaceParam.gobra
src/test/resources/regressions/features/interfaces/proofGenForImport.gobra
src/test/resources/regressions/features/interfaces/proofGenForImportPkg/pkg.gobra
src/test/resources/regressions/features/stubs/stubs1.gobra
src/test/resources/regressions/issues/000232.gobra
src/test/resources/regressions/issues/000408.gobra

Fix interface issues 10 05 22

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000486.gobra

Fix issue 486 (V2)

---

src/main/scala/viper/gobra/translator/encodings/structs/StructEncoding.scala
src/test/resources/regressions/issues/000494.gobra

Add termination measure to `shStructDefault`

---

src/main/scala/viper/gobra/translator/encodings/interfaces/InterfaceEncoding.scala
src/test/resources/regressions/issues/000519.gobra

Fixes #519

---

src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala
src/main/scala/viper/gobra/translator/encodings/typeless/BuiltInEncoding.scala

Fix issue #553.
This will be helpful when https://github.com/viperproject/silicon/pull/651 gets merged

Fix issue 553

---

src/main/scala/viper/gobra/translator/library/fields/FieldsImpl.scala

Made field names more specific

---

src/main/scala/viper/gobra/frontend/Desugar.scala

reduce the exhale permissions from maps in range

---

.github/workflows/license-check.yml
.github/workflows/test.yml
.github/workflows/update-submodules.yml

Fixes warnings emitted by GitHub during CI

Update CI Dependencies

---

src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/test/resources/regressions/examples/disableNL.gobra
src/test/resources/regressions/examples/disableNL_success.gobra

Introduces a flag to disable non-linear integer arithmetic.

Flag for non-linear integer arithmetic

---

src/main/scala/viper/gobra/ast/internal/PrettyPrinter.scala
src/main/scala/viper/gobra/translator/encodings/typeless/TerminationEncoding.scala
src/main/scala/viper/gobra/translator/transformers/TerminationTransformer.scala

* Updates ViperServer from `b7f581a5e74899be27d12359375e7a194d8c89ab` to `f59e00c39c17a4d91c9bc1d6055a24b0814fdb1a`.

Update Submodules to Viper RC 24.01-RC1

---

README.md

@Felalolf and @ArquintL, please add any projects that I might have forgotten

Add verification projects to the README

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000511.gobra

Fix issue 511

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/test/resources/regressions/issues/000777-1.gobra
src/test/resources/regressions/issues/000777-2.gobra

Add purity checks to the ternary expression

---

genparser.sh

This PR optimizes the parser generation script to keep track of the MD5 hashes of all parser dependencies such that the Java files are only generated when the parser actually changes.
Main motivation for this optimization is to save a few seconds of compilation time as the generated files seem to be too different in order for the Java/Scala compiler to realize that a recompilation is not necessary.

Optimize parser generation

---

src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Addressability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Assignability.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/arrays/ArrayEncoding.scala
src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/test/resources/regressions/features/ghost_pointer/ghost-array-fail01.gobra
src/test/resources/regressions/features/slices/slice-boundschecks1.gobra
src/test/resources/regressions/features/slices/slice-boundschecks2.gobra
src/test/resources/regressions/issues/000805.gobra

This PR fixes #805 by adding support for operations over pointers to arrays. In addition, it simplifies some code in neighboring parts of code that was unnecessarily complicated

Fix bug 805

---

src/main/scala/viper/gobra/frontend/info/implementation/property/ConstantEvaluation.scala
src/main/scala/viper/gobra/translator/Names.scala
src/main/scala/viper/gobra/translator/encodings/IntEncoding.scala
src/test/resources/regressions/issues/000858.gobra

depends on https://github.com/viperproject/silver/issues/297

Fix issue 858

---

src/main/scala/viper/gobra/translator/transformers/hyper/SIFLowGuardTransformer.scala
src/test/resources/regressions/issues/000881.gobra

Fix issue 881
