viperproject/gobra

.github/workflows/test.yml

Speeds up compilation of Gobra by caching the sbt version (avoids re-downloading the right sbt version) and by caching compilation output from gobra, viperserver, silicon, carbon, and silver. 
Rerunning the action resulted in a reduction of `sbt test` from 483s to 333s

Better SBT Caching

---

src/main/scala/viper/gobra/frontend/Parser.scala
src/test/resources/regressions/issues/000097.gobra

I changed the parser so that it does not eagerly parse type names and stops too early. For example, the parser now correctly parses the type identifier `intPair` instead of only accepting the prefix `int` and leaving `Pair` to be consumed.

Fixed parsing error mentioned on issue #97

---

src/test/resources/regressions/features/import/multi_import/bar/bar.gobra
src/test/resources/regressions/features/import/multi_import/foo/foo.gobra
src/test/resources/regressions/features/import/multi_import/main1.gobra
src/test/resources/regressions/features/import/multi_import/main2.gobra
src/test/resources/regressions/features/import/multi_import/main3.gobra
src/test/resources/regressions/features/import/multi_import/main4.gobra
src/test/resources/regressions/features/import/multi_import/main5.gobra

Cases described in #40 are already handled by Gobra. However, this PR adds additional test cases to explicitly test these cases.
Note that duplicate identifiers are only lazily detected (see `main4.gobra` and `main5.gobra`)
Closes #40

Additional test cases for per-file imports

---

src/main/scala/viper/gobra/frontend/Parser.scala
src/test/resources/regressions/issues/000035.gobra
src/test/scala/viper/gobra/parsing/ParserUnitTests.scala

A semicolon after the last struct field is now optional
Closes #35

Improves Struct Type Parsing

---

.github/workflows/test.yml

Updates the caching behavior of SBT in CI by forcing a cache update after every run. This should minimize the number of files that need to be recompiled in the next run as the most recent cache version will be used. This change has already been implemented in Gobra IDE and is now coming to Gobra as well.

Improved SBT Caching

---

src/main/scala/viper/gobra/backend/ViperServer.scala

Executing for example the program from #109 currently results in an exception during back-translation.
When using the ViperServer backend (as it is the case for the Gobra IDE) this exception crashes the Akka actor without propagating the exception using the verification promise. Hence, there is no way to gracefully handle such an exception by clients.
This PR catches exceptions during back-translation (when using the ViperServer backend) and propagates them using the verification promise. It is then up to the client to handle the exception.

Exception Handling for ViperServer Backend

---

src/main/scala/viper/gobra/backend/ViperServer.scala

Calling `success` or `failure` on a completed promise results in an IllegalStateException.
Because an exception could occur while reporting any message, the `verificationPromise` might already be completed when the `OverallSuccessMessage` or `OverallFailureMessage` is received.
This PR switches to `trySuccess` and `tryFailure` that result in a no-op if the promise is already completed

Fixes IllegalStateException of ViperServer VerificationPromise

---

.github/license-check/config.json
src/main/resources/README.md
src/main/resources/stubs/github.com/scionproto/scion/go/lib/assert/assert.gobra
src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/frontend/PackageResolver.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/test/resources/regressions/features/stubs/assert/assert-fail1.gobra
src/test/resources/regressions/features/stubs/assert/assert-simple1.gobra

This PR adds `src/main/resources/stubs` to store and use stubs. A simple assertion library taken from (an old version of) SCION is used for demonstration purposes and test cases.
`src/main/resources/README.md` provides a short explanation of the feature and how it influences Gobra's operation
First part of #140

Support for Stubs

---

src/main/scala/viper/gobra/translator/encodings/preds/DefuncComponentImpl.scala
src/main/scala/viper/gobra/translator/implementations/DfltTranslatorConfig.scala

- PredEncoding is added as a typeEncoding
- `instance` only used the arguments but not predicate expression `base`

Defunc Fixes

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000166.gobra
src/test/resources/regressions/issues/000166/bug/importedFile.gobra

Temporary workaround for issue #166 by disabling selective importing, all contents of an imported package appear in the final viper output

Fix issue 166

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMiscTyping.scala
src/test/resources/regressions/issues/000169.gobra
src/test/resources/regressions/issues/000169/pkg2/imported.gobra

Fixes issue #169.
Regarding the case for `MPredicateSpec` in the `GhostMiscTyping.scala`, I did not find an example where Gobra crashes without my change. Nevertheless, I decided to add it for consistency and to avoid any unforeseen bugs due to the use of a wrong context

Fix issue 169

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/BaseTyping.scala
src/test/resources/regressions/issues/000185.gobra

Fixes type checker to not silently skip well-definedness check for declarations if identifier definition is invalid
Fixes #185

Correct type error reporting for short variable declarations

---

src/main/scala/viper/gobra/frontend/PackageResolver.scala

This PR was proposed by @ArquintL. He identified the root cause of the problem and showed me the solution. 
The bug was triggered because every call to `PackageResolver.resolve` would reuse the same stub resources. In the case that the resource was of type `BaseJarResource`, in the second call to `resolve`, the underlying file system would already be closed (due to the reference counting mechanism of `BaseJarResource`) and Gobra would crash in the first call to `retain`, with the message `managed file system can no longer be retained when it is already closed`.
I did not write any test cases for this bug because it was not caught in our testing framework in the first place.

Fix to issue 184

---

src/main/resources/stubs/sync/waitgroup.gobra
src/main/scala/viper/gobra/frontend/info/implementation/typing/StmtTyping.scala
src/test/resources/regressions/examples/parallel_search_replace.gobra
src/test/resources/regressions/examples/parallel_sum.gobra
src/test/resources/regressions/features/defunc/mutex-and-waitgroup1.gobra
src/test/resources/regressions/features/defunc/waitgroup-simple1.gobra

@MartinClochard and I finished the proof of functional correctness of `sum`. This required some changes in the WaitGroup stub to avoid injectivity-related issues in Silver (by introducing `InjEval` and `TokenById` predicates). Besides, I fixed one of the view-shifts (previously called `GenerateToken`, now called `GenerateTokenAndDebt`) to remove one unnecessary pre-condition and introduced a new viewshift (`GenerateToken`) which allows the user to generate `Tokens` without generating the corresponding Debt (this is also a particular case of the debt redistribution rule).

Mutex and waitgroup example

---

src/main/scala/viper/gobra/ast/frontend/PrettyPrinter.scala
src/main/scala/viper/gobra/ast/internal/utility/GobraStrategy.scala
src/main/scala/viper/gobra/ast/internal/utility/Nodes.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/info/base/BuiltInMemberTag.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/Enclosing.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/IdTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostAssignability.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostClassifier.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostLessPrinter.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostWellDef.scala
src/test/resources/regressions/examples/binary_search_tree.gobra
src/test/resources/regressions/examples/tour/Test1.gobra
src/test/resources/regressions/features/ghost_members/ghost-overflows.gobra
src/test/resources/regressions/features/ghost_members/ghost-pure-function.gobra
src/test/resources/regressions/features/multisets/multiset-literal-fail1.gobra
src/test/resources/regressions/features/no_semicolons/ternary_operator/ternary-operator2.gobra
src/test/resources/regressions/features/sequences/seq-contains-fail3.gobra
src/test/resources/regressions/features/sequences/seq-convert-fail4.gobra
src/test/resources/regressions/features/sequences/seq-length-fail2.gobra
src/test/resources/regressions/features/sequences/seq-literal-fail1.gobra
src/test/resources/regressions/features/sequences/seq-range-fail3.gobra
src/test/resources/regressions/features/sequences/seq-slice-fail1.gobra
src/test/resources/regressions/features/sets/set-literal-fail1.gobra
src/test/resources/regressions/features/ternary_operator/ternary-operator2.gobra
src/test/resources/regressions/issues/000128-2.gobra
src/test/scala/viper/gobra/erasing/GhostErasureUnitTests.scala
src/test/scala/viper/gobra/parsing/ParserUnitTests.scala

Adds a binary search tree example with Contains, Insert, and Delete operations.
The example can successfully be ghost erased using the included fixes.
`GhostErasureUnitTests` offers the possibility to write unit tests for ghost erasure and contains test cases for the fixed bugs

Binary Search Tree Example and some Ghost Erasure Fixes

---

src/main/scala/viper/gobra/ast/internal/PrettyPrinter.scala
src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/ast/internal/transform/OverflowChecksTransform.scala
src/main/scala/viper/gobra/ast/internal/utility/GobraStrategy.scala
src/main/scala/viper/gobra/ast/internal/utility/Nodes.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/base/BuiltInMemberTag.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala
src/main/scala/viper/gobra/translator/implementations/translator/BuiltInMembersImpl.scala
src/test/resources/regressions/examples/parallel_search_replace.gobra
src/test/resources/regressions/features/channels/bar/bar.gobra
src/test/resources/regressions/features/channels/channel-fail4.gobra
src/test/resources/regressions/features/channels/channel-fail5.gobra
src/test/resources/regressions/features/channels/channel-fail6.gobra
src/test/resources/regressions/features/channels/channel-simple-buffered1.gobra
src/test/resources/regressions/features/channels/channel-simple4.gobra
src/test/resources/regressions/features/channels/channel-simple5.gobra
src/test/resources/regressions/features/channels/channel-simple6.gobra
src/test/resources/regressions/features/channels/channel-simple7.gobra
src/test/resources/regressions/features/channels/channel-simple8.gobra

@MartinClochard proposed to remove redundant parameters from the `Init` method for channels.
In particular, the new signature is:
```
requires c.IsChannel()
requires c.BufferSize() > 0 ==> (B == pred_true{})
ensures c.SendChannel() && c.RecvChannel()
ensures c.SendGivenPerm() == A && c.SendGotPerm() == B
ensures c.RecvGivenPerm() == B && c.RecvGotPerm() == A
ghost func (c chan T).Init(A pred(T), B pred())
```
As a consequence, `IsChannel` no longer takes the buffer size as a parameter and `BufferSize` is a newly added ghost pure method:
```
requires acc(c.IsChannel(), _)
pure func (c chan T).BufferSize() (k Int)
```
@jcp19 After adapting the type-checker, I've discovered the following bug that is related to type inference for int literals:
If you have `c.Init(0, ...)` in your code and the …

Channel Initialization Improvement

---

src/main/scala/viper/gobra/frontend/info/implementation/TypeInfoImpl.scala
src/main/scala/viper/gobra/translator/encodings/preds/DefuncComponentImpl.scala
src/test/resources/regressions/issues/000164.gobra

Fixes #164. The bug was triggered when local variables with the same name were declared in different functions. In that case, `variables` would return a list with repeated variables. In turn, this would lead to redeclarations of a variable in the same block, in the method `blockD` of the file `Desugar.scala`.
For reference, this is how the current implementation of `blockD` looks like
```scala
def blockD(ctx: FunctionContext)(block: PBlock): in.Stmt = {
val vars = info.variables(block) map localVarD(ctx)
val ssW = sequence(block.nonEmptyStmts map (s => seqn(stmtD(ctx)(s))))
in.Block(vars ++ ssW.decls, ssW.stmts ++ ssW.res)(meta(block))
}
```

Fix issue 164

---

src/test/resources/regressions/examples/dense_sparse_matrix.gobra
src/test/resources/regressions/examples/impl_errors/Tree.gobra
src/test/resources/regressions/examples/impl_errors/dense_sparse_matrix.gobra
src/test/resources/regressions/examples/impl_errors/infinite_list.gobra
src/test/resources/regressions/examples/impl_errors/parallel_search_replace.gobra
src/test/resources/regressions/examples/infinite_list.gobra
src/test/resources/regressions/examples/parallel_search_replace.gobra
src/test/resources/regressions/examples/spec_errors/Tree.gobra
src/test/resources/regressions/examples/spec_errors/dense_sparse_matrix.gobra
src/test/resources/regressions/examples/spec_errors/infinite_list.gobra
src/test/resources/regressions/examples/spec_errors/parallel_search_replace.gobra
src/test/resources/regressions/examples/tour/Tree.gobra
src/test/resources/regressions/examples/zune.gobra

Adds missing return statements and replaces a `:=` by a `=` in `parallel_search_replace.gobra`

Small changes to the examples

---

src/main/resources/README.md
src/main/resources/builtin/builtin.gobra
src/main/resources/builtin/error.gobra
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/PackageResolver.scala
src/main/scala/viper/gobra/frontend/info/Info.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/test/resources/regressions/features/errors/bar/bar.gobra
src/test/resources/regressions/features/errors/error-fail1.gobra
src/test/resources/regressions/features/errors/error-fail2.gobra
src/test/resources/regressions/features/errors/error-simple1.gobra
src/test/resources/regressions/features/errors/error-simple2.gobra
src/test/resources/regressions/features/errors/error-simple3.gobra

This PR adds the possibility to declare built-in members that will be implicitly and unqualifiedly imported in Gobra files.
For caching reasons, only a single "builtin" package is permitted. However, built-in members can be split across multiple files of said package.
In particular, the `error` interface is added as an empty interface as we do not have support for strings yet.
In addition, this PR fixes some contextual bugs in the desugarer that have lead to crashes when encountering an interface located in an imported package. @Felalolf please have a look at commit 23ddbabfda056b4d07f713e1a9f8d368794869dc.
Fixes #158

Implicit Unqualified Imports

---

src/main/scala/viper/gobra/frontend/PackageResolver.scala

In a discussion with @ArquintL, we realized that the logic for keeping track of the number of references to a filesystem in the `ManagedFileSystem` class in the `PackageResolver.scala` file is unnecessarily complex and has led to bugs that are hard to debug (issues #184 and #219) and that are not caught in our CI tests.
Furthermore, the code in question is only used to access the contents of the generated Gobra .jar (more precisely the stubs for the builtin methods in `src/main/resources/builtin/` and standard library methods in `src/main/resources/stubs`). A simpler way to do things would be to keep these two file systems open at all times during the execution of Gobra. This has the additional advantage of avoiding a complex logic for keeping track of references. Unlike the current …

Simplify package resolver

---

.github/license-check/config.json
.github/license-check/headers/CC0-Windows.txt
src/main/scala/viper/gobra/frontend/Parser.scala
src/test/resources/regressions/issues/000225.gobra
src/test/resources/regressions/issues/windows-line-ending/000225.gobra

Fixes issue #225. The parsing bug was caused by the introduction of the following line in a previous commit
```scala
r.replaceAllIn(line, m => StringEscapeUtils.escapeJava(m.group(1) ++ ";" ++ m.group(2)))
```
My understanding is that this causes `CR` characters to be escaped when they appear at the end of a line (e.g. in files created on a Windows machine).
This PR solves the issue by splitting lines on "\r\n|\n" whereas they were previously split only on "\n", which removes the occurrences of "\r\n" before parsing the contents of string literals.

Fix issue 225

---

src/main/resources/stubs/encoding/binary/binary.gobra
src/main/resources/stubs/net/ip.gobra
src/main/resources/stubs/net/net.gobra
src/main/resources/stubs/strconv/atoi.gobra
src/main/resources/stubs/strings/strings.gobra
src/main/resources/stubs/time/time.gobra
src/main/resources/stubs/time/zoneinfo.gobra
src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/ExternalTypeInfo.scala
src/main/scala/viper/gobra/frontend/info/implementation/TypeInfoImpl.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Assignability.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/ConstantEvaluation.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Convertibility.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/test/resources/regressions/features/stubs/stubs-fail0.gobra
src/test/resources/regressions/features/stubs/stubs-fail1.gobra
src/test/resources/regressions/features/stubs/stubs0.gobra
src/test/resources/regressions/features/stubs/stubs1.gobra

This PR adds stubs for some files in packages `encoding/binary`, `net`, `strconv`, `strings` and `time`. The definitions in these files are required for verifying the SCION dataplane.
When deciding what to include in the stubs, I tried to follow these guidelines:
- I opted to include the headers for every exported member in the files, even if those members are severely under-specified. Sometimes, this was not possible (e.g. higher order functions are omitted/commented because there is no support for the function type). 
- I included the definition of non-exported packages in cases where they are useful to verify parts of the implementation of other exported members
- I included the full uncommented body of members whenever they could be fully verified. If they could not for some "small …

Add more stubs

---

src/main/resources/stubs/time/time.gobra

I realized that I introduced some errors in a late commit to the `add-more-stubs` branch. More precisely, the pre-conditions of methods `GobEncode`, `MarshalJSON`, and `MarshalText` in the file `time.gobra` mention the return values. This PR fixes that.

Fix issues with contracts in stubs not detected in tests

---

src/main/scala/viper/gobra/frontend/Config.scala

Currently, Gobra ignores alternative paths to `z3` passed with the `--z3Exe` flag. This happens because the method `merge` in `Config` does not explicitly state how to merge the `z3Exe` fields of two Configurations and thus, it is assigned the default value `None`. This PR fixes that. I also noticed that this happened with the `boogieExe` field and fixed it.

Fix z3 path

---

src/main/scala/viper/gobra/Gobra.scala

Added catch to CLI Gobra instance such that sbt does not have to be restartet on every exception.
For the artifact, we should think about what the output on an exception should be exactly.

Fix crash of Gobra on every exception

---

src/main/resources/stubs/encoding/binary/binary.gobra
src/test/resources/regressions/features/stubs/stubs0.gobra
src/test/resources/regressions/features/stubs/stubs2.gobra

This PR uncomments the bodies of some methods in the `encoding.binary` stub - this can now be done because of the recently added support for bitwise operators. Furthermore, I changed the way `BigEndian` and `LittleEndian` are defined, which allows for calling methods defined for types `bigEndian` and `littleEndian` using the same syntax as in regular Go.

Improve stub for encoding.binary

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/maps/MapEncoding.scala
src/test/resources/regressions/features/maps/maps-simple1.gobra

Currently, Gobra requires access to a map in order to perform a lookup. However, that rules out the possibility of performing a lookup in a nil map, which should always be possible (nil maps are treated as empty maps in Go). This PR addresses that and fixes a couple of other issues.

Fix permission errors when accessing elements of a nil map

---

src/main/scala/viper/gobra/reporting/DefaultErrorBackTranslator.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/main/scala/viper/gobra/translator/implementations/translator/StatementsImpl.scala
src/test/resources/regressions/features/slices/slice-index-fail2.gobra

Currently, "Receiver Not Injective Errors" cause Gobra to provide an unintelligible error message like
```
[info] Encountered an unexpected Viper reason. This is a bug. The following information is for debugging purposes:
[info]   Receiver of (ShArrayloc((sarray((ShStructget13of14(s_slayers_V10_CN17): Ref).val$_Slice_Ref): ShArray[Ref]), sadd((soffset((ShStructget13of14(s_slayers_V10_CN17): Ref).val$_Slice_Ref): Int), i_slayers_V17)): Ref).val$_Int [scion.gobra@423.65--423.71]  might not be injective.
[info]     error is ReceiverNotInjective
[info]     error offending node = (ShArrayloc((sarray((ShStructget13of14(s_slayers_V10_CN17): Ref).val$_Slice_Ref): ShArray[Ref]), sadd((soffset((ShStructget13of14(s_slayers_V10_CN17): Ref).val$_Slice_Ref): Int), i_slayers_V17)): Ref).val$_Int
[info] …
```

Add ReceiverNotInjectiveReason for injectivity errors

---

src/main/resources/stubs/net/iprawsock.gobra
src/main/resources/stubs/net/net.gobra
src/main/resources/stubs/net/udpsock.gobra
src/test/resources/regressions/features/stubs/stubs0.gobra
src/test/resources/regressions/features/stubs/stubs1.gobra

This PR improves introduces a `mem()` predicate  in every interface defined in the `net.gobra` file. Furthermore, it adds two new files (`iprawsock.gobra` and `udpsock.gobra`) with definitions useful to verify scion. In these two files, the signal to noise ratio may be rather small, as I did not bother verifying members which are not immediately useful to my ends on verified scion or which rely on unsupported features of Gobra.

Improve specification of the net stub

---

.github/workflows/test.yml
artifact/Dockerfile
src/main/resources/stubs/net/net.gobra
src/main/scala/viper/gobra/backend/Carbon.scala
src/main/scala/viper/gobra/translator/implementations/translator/BuiltInMembersImpl.scala
src/test/resources/regressions/features/defunc/waitgroup-simple1.gobra
src/test/resources/regressions/features/fractional_permissions/perm-fail1.gobra

Updates to latest Viper release.
Currently, this PR tests against the release candidate but will be updated to the release when it's out.

Update Viper Dependencies to 'v.21.07-release'

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostTypeTyping.scala
src/test/resources/regressions/features/maps/maps-declared-type-simple1.gobra
src/test/resources/regressions/features/maps/math-maps-declared-type-simple1.gobra
src/test/resources/regressions/features/multisets/multiset-declared-type-simple1.gobra
src/test/resources/regressions/features/multisets/multiset-type-simple2.gobra
src/test/resources/regressions/features/options/options-declared-type-simple1.gobra
src/test/resources/regressions/features/sequences/seq-declared-type-simple1.gobra
src/test/resources/regressions/features/sequences/seq-type-simple2.gobra
src/test/resources/regressions/features/sets/set-declared-type-simple1.gobra
src/test/resources/regressions/features/sets/set-type-simple2.gobra

Previously, declared types have not been allowed for the data structures mentioned in the title.
This PR removes these (artificial) restrictions and adds corresponding test cases checking that the encoding works properly.

Mathematical Maps, Sets, Multisets, Options, and Sequences with Declared Types

---

src/main/resources/stubs/net/iprawsock.gobra
src/main/resources/stubs/net/udpsock.gobra
src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000341/pkg1/f1.gobra
src/test/resources/regressions/issues/000341/pkg2/f2.gobra

The problem is in the way we combine fields from the different desugarers during Desugaring. In particular, the current way it is implemented may make Gobra "forget" about interface implementations in imported packages.

Fix issue #341

---

src/main/resources/stubs/encoding/binary/binary.gobra

Changes:
- The PutUint methods of the interface `ByteOrder` in package `encoding/binary` have been extended with the `decreases` keyword

verified termination of PutUint methods in encoding/binary

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/backend/BackendVerifier.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/Gobrafier.scala
src/main/scala/viper/gobra/frontend/PackageResolver.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/Source.scala
src/main/scala/viper/gobra/frontend/info/Info.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/main/scala/viper/gobra/reporting/DefaultMessageBackTranslator.scala
src/main/scala/viper/gobra/reporting/Message.scala
src/main/scala/viper/gobra/reporting/Reporter.scala
src/main/scala/viper/gobra/translator/Translator.scala
src/test/scala/viper/gobra/BenchmarkTests.scala
src/test/scala/viper/gobra/DetailedBenchmarkTests.scala
src/test/scala/viper/gobra/GobraPackageTests.scala
src/test/scala/viper/gobra/GobraTests.scala
src/test/scala/viper/gobra/OverallBenchmarkTests.scala
src/test/scala/viper/gobra/erasing/GhostErasureUnitTests.scala
src/test/scala/viper/gobra/typing/ExprTypingUnitTests.scala
src/test/scala/viper/gobra/typing/TypeTypingUnitTests.scala

This PR adapts Gobra to take a vector of `Source` instead of `Path` as input. This provides greater flexibility as a `Source` can either represent a file or simply some string. In particular, it allows Gobra Server to invoke Gobra with some (file)content that is not necessarily stored in local files.
Not however that this does not immediately enables Gobra Server to run on a remote machine as the entire import resolution mechanism still relies on the local filesystem. A proper abstraction would need to be implemented (e.g. with callbacks to query the directory structure and/or to retrieve files).

Switch from Paths to Sources

---

src/main/resources/stubs/errors/wrap.gobra

As Is:
- errors package is not supported
To Be:
- adds stubs for the errors.Is, errors.As, and errors.Unwrap methods

added stubs for As, Is, and Unwrap methods of errors package

---

src/main/resources/stubs/strconv/atoi.gobra
src/main/resources/stubs/strconv/itoa.gobra

As Is:
- termination of the methods in `strconv` isn't verified
To Be:
- verified termination of methods in `strconv`

added termination contracts to the strconv package

---

src/main/scala/viper/gobra/backend/Backend.scala
src/main/scala/viper/gobra/backend/BackendVerifier.scala
src/main/scala/viper/gobra/backend/Carbon.scala
src/main/scala/viper/gobra/backend/Silicon.scala
src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/backend/ViperServer.scala
src/main/scala/viper/gobra/backend/ViperVerifier.scala
src/main/scala/viper/gobra/frontend/Config.scala

Adapts ViperServer backend (reintegrated by @jogasser) to be usable by Gobra Server. In particular, Gobra Server creates a ViperCoreServer instance as part of its initialization. This PR enables Gobra Server to pass this server instance to either `ViperServerWithSilicon` or `ViperServerWithCarbon` instead of a new server instance being created.
Furthermore, `ViperVerifierConfig` has been removed as I've introduced it back then to route configuration options via Gobra to the backend but this does not seem to be necessary anymore and reduces complexity.

ViperServer Backend Improvements

---

docs/tutorial.md
project/build.properties
src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/ast/frontend/PrettyPrinter.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMiscTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GoifyingPrinter.scala
src/test/resources/regressions/features/trusted/trusted-functions.gobra
src/test/resources/regressions/features/trusted/trusted-methods.gobra
src/test/scala/viper/gobra/DetailedBenchmarkTests.scala
src/test/scala/viper/gobra/parsing/ParserUnitTests.scala
src/test/scala/viper/gobra/typing/ExprTypingUnitTests.scala
src/test/scala/viper/gobra/typing/TypeTypingUnitTests.scala

- Adds a trusted flag to Gobra, which lets a user assume that the specification of a method or function holds without checking it. To achieve this, it ignores the body of the function or method
- Upgrades sbt to 1.5.7 to fix log4j CVE(see, https://www.scala-lang.org/blog-detail/2021/12/16/state-of-log4j-in-scala-ecosystem.html for more details)

Trusted Flag

---

.github/license-check/config.json
GobraChopper.conf
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/util/ChopperUtil.scala
src/main/scala/viper/gobra/util/ViperChopper.scala
src/test/scala/viper/gobra/chopper/SCCUnitTests.scala

Extension of chopper where (for at least 10 isolated vertices) an additional SCC transformation is used. 
The advantage of the SCC is that it decreases the size of the graph later steps work on, in particular the merging step.
To check correctness, I did ran all tests with the chopper enabled, which succeeded. If you are currious, this took 47 minutes, which is 4 minutes slower than the current time on master.

Chopper with scc

---

src/main/resources/stubs/net/ip.gobra
src/main/resources/stubs/net/iprawsock.gobra
src/main/resources/stubs/net/net.gobra
src/main/resources/stubs/net/udpsock.gobra
src/main/resources/stubs/strconv/atoi.gobra
src/main/resources/stubs/strconv/itoa.gobra
src/main/resources/stubs/strings/strings.gobra
src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/translator/encodings/FloatEncoding.scala
src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala

This PR introduces small changes to the std lib (mostly termination measures) that are helpful to verify the SCION codebase. After this PR, the verified scion branch and master should be on par, with the exception of the support for the outline keyword (merged in the scion branch, not merged on master) which does not work well anyway.

Std lib changes from the verifiedSCION branch

---

src/main/scala/viper/gobra/frontend/info/implementation/resolution/NameResolution.scala
src/test/resources/regressions/features/interfaces/ghostMembers.gobra

Previously, `ghost` annotations in an interface have not been correctly taken into account. In the added test case, Gobra used to complain that the implementation method is `ghost` but the declared method in the interface is not.

Ghost Interface Methods

---

src/main/scala/viper/gobra/frontend/Parser.scala
src/test/resources/regressions/features/maps/math-maps-simple2.gobra

Still a PR for the old parser but I need the following 3 improvements:
- keep bodies of pure functions & methods in imported packages (saves writing an artificial postcondition with the same assertion)
- 'ghost' can be on its own line in interface declarations (thus, one can write similar looking spec as one is used to write for regular functions/methods)
- ghost types can be parsed as one would expect. Without this change, the newly created test case could not be parsed
@jcp19 does the first improvement cause performance problems in VerifiedSCION? Alternatively, we could introduce an annotation `transparent` or `opaque` (depending on what the default should be) or a CLI option such that the behavior could be controlled

Parser Improvements

---

src/main/scala/viper/gobra/ast/frontend/AstPattern.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/AmbiguityResolution.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/test/resources/regressions/features/interfaces/predicateWithInterfaceParam.gobra

Using a struct for an interface parameter in function performs an implicit conversion `toInterface` such that the encoded Viper program is well typed. This implicit conversion is however not done for predicates, which is fixed by this PR.
The added unit test illustrates the problem best

Implicit Conversion for Predicate Arguments

---

src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/main/scala/viper/gobra/translator/implementations/components/ConditionsImpl.scala
src/test/resources/regressions/issues/000401.gobra
src/test/resources/regressions/issues/000402.gobra

Adds termination measures to the viper functions generated from file `ConditionsImpl.scala` and adds a termination measure to the viper function `nilSlice` generated from the file `SliceEncoding.scala`.
Furthermore, I improved the documentation of functions in `SliceEncoding.scala` by adding `decreases` clauses where they were missing.
Closes #401 
Closes #402

Fixes 401 and 402

---

src/main/scala/viper/gobra/ast/frontend/AstPattern.scala
src/main/scala/viper/gobra/frontend/info/base/BuiltInMemberTag.scala
src/main/scala/viper/gobra/frontend/info/base/SymbolTable.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostStmtTyping.scala
src/test/resources/regressions/features/predicates/foldability.gobra

Strengthens foldability checks within Gobra to avoid situations in which Silicon would crash while unfolding an abstract predicate

Predicate Foldability

---

.gitignore
src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/frontend/InformativeErrorListener.scala
src/main/scala/viper/gobra/frontend/ParseTreeTranslator.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/ReportFirstErrorStrategy.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Addressability.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/BuiltInMemberTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/IdTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/test/scala/viper/gobra/erasing/GhostErasureUnitTests.scala

The last PRs introduced some compiler warnings. This PR addresses those that I could fix quickly, and introduces some simplifications. The remaining issues have to do with the way we pattern match against nested generic types, which is not sound due to erasure. I could just introduce an annotation to ignore those, but I would rather go with a better solution.

Fix some compiler warnings

---

src/main/java/viper/gobra/frontend/GobraParserBase.java
src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/frontend/InformativeErrorListener.scala
src/main/scala/viper/gobra/frontend/ParseTreeTranslator.scala
src/main/scala/viper/gobra/frontend/ReportFirstErrorStrategy.scala

- Fixes positional information (end position was 1 character too early in the program text)
- Reports all errors occurred during parsing (thanks to @nicoberling for the fix)

Parser Fixes

---

src/main/scala/viper/gobra/frontend/Config.scala
src/test/scala/viper/gobra/GobraPackageTests.scala

The CLI options contain various redundant options that probably nobody uses. This PR removes them. It should be merged after #434 to avoid conflicts.
Previous output of running gobra with `--help`:
```
[info]  Usage: Gobra -i <input-files or a single package name> [OPTIONS]
[info]  Options:
[info]       --backend  <arg>              Specifies the used Viper backend, one of
[info]                                     VSWITHSILICON, VSWITHCARBON, SILICON, CARBON
[info]                                     (default: SILICON)
[info]       --boogieExe  <arg>            The Boogie executable
[info]       --cacheFile  <arg>            Cache file to be used by Viper Server
[info]       --chop  <arg>                 Number of parts the generated verification
[info] …
```

Cleanup config options

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/Source.scala

Right now, the identifiers obtained in the encoding are so big that reading the generated viper file for debugging is very hard. This PR tackles that problem in two fronts:
1. remove the viper id from the identifiers of local variables - @ArquintL maybe I'm missing something, but I do not see the purpose in including this in every local variable
2. (less impactful) use base64 instead of hexadecimal to print the hashsum of the package identifier when needed, which should lead to smaller names

Reduce the size of names in the encoding

---

src/main/scala/viper/gobra/translator/implementations/translator/BuiltInMembersImpl.scala
src/test/resources/regressions/features/builtin/copy-fail2.gobra
src/test/resources/regressions/features/builtin/copy-fail3.gobra
src/test/resources/regressions/features/builtin/copy-simple1.gobra
src/test/resources/regressions/features/builtin/copy-simple2.gobra

Our current encoding of `copy` handles all cases supported in Go, including the case when the src and dst are overlapping. The spec is more complicated to deal with this particular (rarely used) case. As it stands, it is also triggering often matching loops. To avoid that problem for now, this PR disables those. This is a temporary solution, until we design a more careful spec for all cases

Simplify 'copy' function to avoid matching loops

---

src/main/scala/viper/gobra/ast/internal/transform/CGEdgesTerminationTransform.scala

There is a cast missing currently that causes the generated viper code (i.e., with flag `--printVpr`) to not be well-formed. This PR addresses that.

Fix encoding problem with termination checking

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/frontend/PackageResolver.scala
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/frontend/Source.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/test/scala/viper/gobra/BenchmarkTests.scala
src/test/scala/viper/gobra/DetailedBenchmarkTests.scala
src/test/scala/viper/gobra/GobraPackageTests.scala
src/test/scala/viper/gobra/reporting/StatsCollectorTests.scala

Unifies source file search for inputs and imports and fixes filtering of path containing `testdata`

Input File Filtering

---

src/main/scala/viper/gobra/frontend/ParseTreeTranslator.scala

This PR fixes a bug where int8 would be parsed as a named operand and not as a type. It was just a missing case in a match construct.

fix bug where int8 would be parsed as named operand

---

src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala

This PR would optimally be combined with PR #409, but we can merge it already. When #409 is merged, we should adapt the default value of the option and its description. (This option should exist though even after we merge #409, as it might be necessary to verify already existing codebases like SCION)
PS: We can merge this after merging #434 to avoid more changes in that PR

Add options to assume Injectivity On Inhale and to disable it

---

src/main/scala/viper/gobra/frontend/PackageResolver.scala
src/main/scala/viper/gobra/frontend/Source.scala
src/main/scala/viper/gobra/frontend/info/Info.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala
src/test/resources/regressions/issues/000416.gobra
src/test/resources/regressions/issues/000416/importedImplementationPkg/importedImplementationPkg.gobra
src/test/resources/regressions/issues/000416/importedImplementationPkg/shape/shape.gobra

Fixes #416 
The problem was that AbstractImport does not uniquely identify a package. In the example, the package shape was parsed twice, once for the import path "shape" and once for the import path "importedImplementationPkg/shape". To fix this I introduce the indirection AbstractPackage which is supposed to uniquely identify a package. It is not clear to me whether tjhe last folder of the import path is always sufficient, e.g. using "shape" for ".../shape". In this PR, I use the canonical path of the directory the package is stored in, which might be overkill.

Fix issue 416

---

src/main/resources/builtin/builtin.gobra
src/main/scala/viper/gobra/frontend/info/implementation/resolution/Enclosing.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/MemberResolution.scala

This PR introduces a predicate `ErrorMem` in the `error` interface. An instance of this predicate is required to be able to call the `Error` method.
This PR also addresses the cyclic import error that is caused when `ErrorMem` is introduced. To solve that, we remove the call to method `tryUnqualifiedBuiltInPackageLookup` in method `tryUnqualifiedPackageLookup` when the importing package is `builtin`.

Add Mem predicate in Error

---

src/test/resources/regressions/examples/parallel_search_replace_shared.gobra

Adds `parallel_search_replace_shared.gobra`, which is a modification of `parallel_search_replace.gobra`. It uses shared instead of exclusive variables in the `worker` function.
- `parallel_search_replace.gobra` takes 60-66sec on my machine
- `parallel_search_replace_shared.gobra` takes 110-121sec on my machine

Example using Shared Variables

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/ExternalTypeInfo.scala
src/main/scala/viper/gobra/frontend/info/implementation/TypeInfoImpl.scala
src/test/resources/regressions/features/globals/impl-shorthand-fail01.gobra
src/test/resources/regressions/features/globals/impl-shorthand-fail02.gobra
src/test/resources/regressions/features/globals/impl-shorthand-simple01.gobra

A typical pattern in some Go codebases is to add lines like the following to enforce that `ImplType` is an implementation of `InterfaceType`.
```go
var _ InterfaceType = ImplType(nil)
```
Because this does not have any effect at runtime, we can already add support for it without the more in-depth support for global variables. Having the line above is also compatible with explicitly providing an implementation proof in Gobra.

Add support for short-hand for implementation proofs

---

src/main/scala/viper/gobra/translator/encodings/interfaces/InterfaceEncoding.scala
src/test/resources/regressions/features/interfaces/pointerAndTypeImplementing.gobra

Trying to implement an interface for both a type and a pointer to the same type generated two functions implementing the interface with the same name. To fix this bug, an extra parameter to proofName was added containing the type of the receiver.

add variable to proofName to generate unique names

---

src/main/resources/builtin/builtin.gobra

In Go (1.18), the type `any` is an alias for `interface{}`.

Aliased type for any = interface{}

---

src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/test/resources/regressions/features/defer/defer-simple-04.gobra

Just noticed that `defer` cannot be used in ghost contexts, which is useful when deferring a fold/unfold.

Make `defer` statement ghostifiable

---

src/main/scala/viper/gobra/translator/encodings/interfaces/TypeComponentImpl.scala
src/test/resources/regressions/features/runes/type-equality.gobra

As it stands, Gobra generates repeated occurrences of the following four functions, corresponding to the type tags of `int32` and `rune` (its synonym), and `int8` and `bytes` (also synonyms) (for some reason, this problem was never triggered in the CI before). This PR addresses that.
```
function int32_Types(): Types
unique function int32_Types_tag(): Int
function byte_Types(): Types
unique function byte_Types_tag(): Int
```

Fix duplicate type tags in the encoding

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/TypeTyping.scala
src/test/resources/regressions/features/arrays/array-type-simple5.gobra
src/test/resources/regressions/issues/000480.gobra

As discussed with @Felalolf, the current array encoding should be compatible with "custom declared types". This PR removes the type-checker's check that keeps one from declaring arrays of declared types.

Add support for arrays of custom declared types

---

src/main/scala/viper/gobra/translator/encodings/arrays/ArrayEncoding.scala
src/test/resources/regressions/issues/000489.gobra

Fix issue #489

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/reporting/StatsCollector.scala

Currently, the flag `--gobraDirectory`/`-g` is ignored entirely. This PR addresses that and adds an informative message when the stats.json file cannot be written. Furthermore, I cleaned-up the messages that are shown after Gobra has executed, to make it nicer to use.

Fix gobraDirectory and change severity of the warnings

---

.gitignore
genparser.sh

Generating the parser is currently annoying. This script makes things a bit easier.

Add script to generate parser

---

src/main/scala/viper/gobra/translator/encodings/interfaces/InterfaceEncoding.scala

It is very common to compare an interface value with the literal `nil`. Currently, this comparison is encoded as an equality, preceded by a check that one of the operands is comparable. This check is redundant and I removed it in this PR.

Remove redundant checks when comparing interfaces with the `nil` literal

---

src/main/scala/viper/gobra/translator/util/ViperUtil.scala

Our encoding currently introduces unnecessary occurrences of the `true` literal. This PR eliminates those that are created by the method `bigAnd`.

Remove unnecessary occurrences of the 'true' literal

---

src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala

In some cases in SCION, I observed that not passing the flag `--enableMoreCompleteExhale` to silicon improves performance drastically, without any observable side effects. This PR introduces a way to disable this default behaviour whenever desired.

Add option to disable the behaviour of "moreCompleteExhale"

---

src/main/scala/viper/gobra/backend/BackendVerifier.scala
src/main/scala/viper/gobra/reporting/Message.scala

Currently, chopping a program in multiple parts causes all parts to be verified sequentially. This PR enables concurrent verification of those parts.

Verify chopped parts in parallel

---

.gitignore
src/main/scala/viper/gobra/frontend/Parser.scala
src/main/scala/viper/gobra/reporting/Reporter.scala

If `unparse` is enabled, `.gobrafied` files will be created with the gobrafied content of the input files.
This is useful to count the number of lines of specification in the following way:
LOC = lines of code of a `.go` file counted by the usual tools
LOS = lines of code of a `.gobrafied` file - LOC + hybrid lines
A hybrid line is a line that contains actual code and annotations. The following command can be used to count these hybrid lines:
```
awk 'fname != FILENAME { printf "%s: %s\n", fname, count; fname = FILENAME; count = 0 } /.*\/\*@.*@\*\/.*/ { count++; total++ } END { print total }' $(find . -name '*.go' -or -name '*.gobra')
```

Create gobrafied debug files

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/ast/internal/transform/ConstantPropagation.scala

This PR introduces an optimization that reduces the size of the emitted Viper code by folding all constants. Doing this allows us to save a domain definition and one domain function per constant

Constant propagation

---

src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala

Currently, the `String` domain is always generated, even if it is not used because function `strSlice` is marked as non-lazy. This PR addresses that.

Fix lazy generation of the string domain

---

src/main/scala/viper/gobra/reporting/Message.scala
src/main/scala/viper/gobra/translator/Translator.scala
src/main/scala/viper/gobra/translator/transformers/TerminationTransformer.scala

This PR optimizes the import of axioms for termination measures to only import those that are actually needed based on the type of termination measure tuples.
Furthermore, this PR sorts the Viper members reported by `GeneratedViperMessage`

Improving the Import of Termination Axioms

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/features/purefuncs/unused-result.gobra

@jcp19 I'm not feeling super confident with the writer pattern, so please take a look.

Fixes Pure Function Calls whose Result is Unused

---

src/main/scala/viper/gobra/frontend/Config.scala

This PR adds another flag to `BaseConfig` to execute all steps in Gobra except for verifying the program. This flag is useful for Gobra-IDE because we split verification into two steps -- encoding the input into a Viper AST and actually verifying the Viper AST

Allow BaseConfig to skip verification

---

src/test/resources/regressions/examples/evaluation/dense_sparse_matrix.gobra
src/test/resources/regressions/examples/evaluation/heapsort.gobra
src/test/resources/regressions/examples/evaluation/impl_errors/heapsort.gobra
src/test/resources/regressions/examples/evaluation/impl_errors/parallel_search_replace.gobra
src/test/resources/regressions/examples/evaluation/spec_errors/heapsort.gobra

As reported in issue #234, some of our tests seem to not terminate non-deterministically. This PR disables a few of them that are stalling our CI

Disable problematic tests

---

src/main/scala/viper/gobra/translator/context/Context.scala
src/main/scala/viper/gobra/translator/encodings/combinators/TypeEncoding.scala
src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala

Currently, our slice literals introduce unnecessary proof obligations.
```go
func test() {
var s []int
s = []int{1, 2, 3}
}
```
For this example, the currently generated Viper method is
```
method test_7b972028_F()
{
// decl 
// decl s_V0: []int°, N0: []int°
var N0: Slice[Ref]
var s_V0: Slice[Ref]
// init s_V0
inhale s_V0 == sliceDefault_Intint$$$_S_$$$()
// s_V0 = dflt[[]int]
s_V0 := sliceDefault_Intint$$$_S_$$$()
// N0 = new([]int { 0:1, 1:2, 2:3 })
var fn$$2: Emb_3_Intint$$$_S_$$$
var fn$$3: Emb_3_Intint$$$$_E_$$$
var fn$$0: Emb_3_Intint$$$_S_$$$
fn$$2 := fn$$0
fn$$3 := arrayDefault_3_Intint$$$$_E_$$$()
inhale (forall fn$$1: Int ::
{ (ShArrayloc(unbox_Emb_3_Intint$$$_S_$$$_ShArray_Ref(fn$$0), fn$$1): Ref) }
0 <= fn$$1 && fn$$1 < 3 ==> …
```

Simplify encoding of `NewSliceLit`

---

src/main/scala/viper/gobra/translator/encodings/maps/MapEncoding.scala

Changes:
- Generates as many fields as possible to represent different map types, instead of generating a single field called `underlyingMapField`. Should have performance implications like PR #568. (This is somewhat confirmed by our experiments with SCION, where verifying a pacakge that uses maps heavily went down from 17min to 12)
- Removes one level of indirection which, in hindsight, does not seem to be necessary (through the `getMap` function)
In a separate PR, I plan to generate more auxiliary functions for `len` and `lookup`, which should expose better triggers at the surface language
PS: some trivial changes like inserting spaces and what not happened because my IDE decided randomly that it is good to automatically apply a code style now -.-

Optimize map encoding

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Executability.scala
src/test/resources/regressions/features/channels/channel-fail9.go

Gobra rejects the following program with a type error because the receive operation is not considered executable:
```go
func c() <-chan struct{}
func test1() {
<-c()
}
```
This PR addresses that

Make `receive` executable

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/backend/BackendVerifier.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/reporting/StreamingReporter.scala

Instead of printing the  verification errors after the verification for each package ends, stream them.

Streaming errors

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/adts/AdtEncoding.scala
src/test/resources/regressions/features/adts/termination-fail1.gobra
src/test/resources/regressions/features/adts/termination-success1.gobra

This PR introduces support for expressions of the form `len(e)`, where `e` is an expression of an ADT type. This computes the rank of `e`, as defined in [Paul Dahlke's thesis](https://ethz.ch/content/dam/ethz/special-interest/infk/chair-program-method/pm/documents/Education/Theses/Paul_Dahlke_BA_Report.pdf), which is a useful termination measure for functions defined by structural recursion on an ADT instance.
Arguably, it is bad style to overload `len` here for this measure but I would argue that this is consistent with the other overloads of `len` in Go and Gobra, e.g. for things like channels, maps (part of Go) and sets (part of Gobra). Nonetheless, I could introduce a new node if the majority dislikes this design, although this would introduce a new reserved keyword.

Introduce `len` for ADTs to be used as a termination measure

---

src/main/scala/viper/gobra/translator/library/slices/SlicesImpl.scala

More precise triggers for smake

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/frontend/Config.scala

1. print the time when a verification job starts
2. introduce the --noVerify flag to skip verification. Useful when we are only interested in generating the viper file

QoL improvements

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/TypeInfo.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostWellDef.scala
src/test/resources/regressions/features/conversion/conversion-fail01.gobra
src/test/resources/regressions/features/conversion/conversion-simple01.gobra

Currently, type conversions cannot have ghost child nodes. This is unnecessarily restrictive. This PR lifts such a restriction and allows non-effectful conversions to be used in spec.

Allow non-side-effectful conversions in spec

---

src/main/resources/builtin/builtin.gobra

The version of error introduced in the previous spec caused a big performance degradation in verifiedSCION (likely, due to the use of wildcards in the spec of `Error`. This PR addresses that and recovers the original expressivity of the `error` type (in particular, implementations of `Error` that mutate the underlying data structure are still allowed)

Better error spec

---

src/main/scala/viper/gobra/reporting/VerifierError.scala
src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/main/scala/viper/gobra/translator/util/MethodGenerator.scala
src/test/resources/regressions/features/make_and_new/make1.gobra

Instead of encoding calls to `make` for slices as a sequence of exhales and inhales that encode a function call, this PR generates a method instead and encodes the calls to make at the Gobra level as method calls to the generated method.
This is the first of a few PRs I have in mind to make the Viper code generated by Viper more readable

Encode slice `make` as a method call

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/arrays/ArrayEncoding.scala
src/main/scala/viper/gobra/translator/encodings/arrays/SharedArrayComponentImpl.scala
src/main/scala/viper/gobra/translator/encodings/combinators/TypeEncoding.scala
src/main/scala/viper/gobra/translator/encodings/defaults/DefaultGlobalVarEncoding.scala
src/main/scala/viper/gobra/translator/encodings/sequences/SequenceEncoding.scala
src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/main/scala/viper/gobra/translator/encodings/structs/StructEncoding.scala
src/main/scala/viper/gobra/translator/library/embeddings/EmbeddingComponent.scala
src/main/scala/viper/gobra/translator/util/ViperUtil.scala
src/test/resources/regressions/issues/000621.gobra

Turns out some termination measures were missing in a function in the array encoding

Fix issue 621

---

src/main/scala/viper/gobra/frontend/info/base/Type.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/IdTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/TypeTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostIdTyping.scala
src/test/resources/regressions/issues/000651.gobra

When an `ADTClauseT` is built, we first accumulate all the fields in a map from identifiers to the corresponding field type. However, this map does not preserve the order in which the fields are declared. In rare cases, the iteration order will actually differ from the order in which fields are declared, which can lead to ill-formed Viper programs being emited.

Fix issue 651

---

src/main/scala/viper/gobra/backend/Silicon.scala
src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala

Markus noticed a speedup when running silicon with Z3 via API in scion generated files.

Add flag to use Z3 via API

---

src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/main/scala/viper/gobra/translator/library/slices/SlicesImpl.scala

The slice encoding was missing the following termination measures:
- In function sadd
- In function sconstruct

Missing termination measures

---

src/main/scala/viper/gobra/ast/internal/PrettyPrinter.scala
src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Addressability.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/theory/Addressability.scala
src/main/scala/viper/gobra/translator/encodings/typeless/AssertionEncoding.scala
src/test/resources/regressions/features/let/let_simple.gobra

This PR allows us to write assertions such as the following:
```go
let z := y in Q(z)
let z := x in acc(z)
```
So far, these assertions were rejected because `Q(z)` and `acc(z)` are not strongly pure.
Furthermore, I moved the desugaring of strongly pure let expressions from `exprD` to `ghostExprD`

Enable let expressions with weakly pure subexpressions

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/translator/context/Context.scala
src/main/scala/viper/gobra/translator/context/DfltTranslatorConfig.scala
src/main/scala/viper/gobra/translator/encodings/combinators/FinalTypeEncoding.scala
src/main/scala/viper/gobra/translator/encodings/combinators/TypeEncoding.scala
src/main/scala/viper/gobra/translator/encodings/combinators/TypeEncodingCombiner.scala
src/main/scala/viper/gobra/translator/encodings/defaults/DefaultTriggerExprEncoding.scala
src/main/scala/viper/gobra/translator/encodings/maps/MapEncoding.scala
src/main/scala/viper/gobra/translator/encodings/typeless/AssertionEncoding.scala
src/main/scala/viper/gobra/translator/util/ViperWriter.scala
src/test/resources/regressions/features/maps/maps-simple1.gobra

This PR extends the `TypeEncoding` with a method `triggerExpr` that is now used to encode expressions that occur in triggers (instead of encoding them with `expression`). This allows us to select well-formed triggers whenever the `expression` encoding generates ill-formed triggers. With this, we solve a long-standing issue where triggers containing a a map (like `m[i]` or `i in range(m)`) are translated to invalid triggers at the Viper level.
Besides, this PR introduces two quality of life improvements
- like in Viper, we now support the idiom `key in m`, where `m` is a map, whereas before we would have had to write `key in domain(m)`. The previous idiom is still supported.
- the `assert` method in `ViperWriter` has been simplified to not generate a call to `assert` whenever the condition …

Improvements in maps

---

src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/translator/Names.scala
src/test/resources/regressions/features/maps/maps-nested.gobra
src/test/resources/regressions/features/options/options-nested-maps.gobra

Our treatment of expressions with type `InternalSingleMulti(t, ms)` is very iffy atm, leading to issues like those reported in #694. This PR addresses the issue in part. It allows progress on VerifiedSCION to continue, but I recognize that extending this solution to the entire type system is cumbersome. Ideally, we would have a more systematic way to deal with expressions of this type.

Treat values of type InternalSingleMulti(t, ms) as t for nested dictionaries

---

src/main/scala/viper/gobra/reporting/VerifierError.scala
src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala
src/test/resources/regressions/issues/000695.gobra

This PR fixes issue #695.
We drop the violation in the channel encoding as the type-checker is anyway more lenient and allows messages of types that are *assignable* (and not necessarily equal) to the channel type.
However, this change requires a small change to the channel encoding as we can no longer use the message's type when constructing the pure method calls to the channel's invariant getters (`SendGivenPerm`, `SendGotPerm`, `RecvGivenPerm`, and `RecvGotPerm`) but have to use the channel type instead (as they are not necessarily equal anymore).

Fixes #695

---

src/main/scala/viper/gobra/ast/internal/PrettyPrinter.scala
src/test/scala/viper/gobra/GobraTests.scala

Pretty printing a termination measure consisting of a predicate instance results in a violation. This PR fixes the pretty printer and adapts the (single-package) unit tests to print Gobra messages, which in turn triggers pretty-printing of ASTs contained in these messages, thus hopefully preventing similar errors in the future.

Fixes Pretty Printer

---

src/main/resources/stubs/net/ip.gobra
src/main/resources/stubs/net/net.gobra
src/main/resources/stubs/strings/strings.gobra
src/main/resources/stubs/sync/mutex.gobra
src/main/resources/stubs/sync/waitgroup.gobra
src/main/scala/viper/gobra/frontend/Config.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/MemberTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostMemberTyping.scala
src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala
src/test/resources/regressions/examples/tutorial-examples/basicAnnotations.gobra
src/test/scala/viper/gobra/GobraPackageTests.scala
src/test/scala/viper/gobra/GobraTests.scala
src/test/scala/viper/gobra/erasing/GhostErasureUnitTests.scala
src/test/scala/viper/gobra/reporting/StatsCollectorTests.scala

In the past, we run into unsoundnesses and tricky corner cases of Gobra because, so far, we were able to use non-terminating functions in specifications. This PR changes the default behaviour of Gobra to expect a termination measure in any pure function or method. Please let me know if you agree with this being the default behaviour. Notice that I did not adapt all of the current tests. This can be done but it would take more time than I am willing to spend atm.

Check by default that all pure and ghost functions have termination measures

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/test/resources/regressions/issues/000697.gobra
src/test/resources/regressions/issues/000697/pkg/pkg.gobra

Fixes #697

---

.github/workflows/test.yml

Recently upgrading the `docker/build-push-action` action changed how published Gobra images appear ([before](https://github.com/viperproject/gobra/pkgs/container/gobra/71107123?tag=v23.02), [after](https://github.com/viperproject/gobra/pkgs/container/gobra/176513635)).
This seems to be related to multi-architecture Docker images and also manifests as an additional architecture called `unknown/unknown` (cf. [this issue](https://github.com/docker/build-push-action/issues/900)).
While the immediate workaround is fairly simple, i.e., setting `provenance: false` for this action, I took the opportunity to add several other meta-information about our images according to the [OpenContainers Annotation Spec](https://specs.opencontainers.org/image-spec/annotations/). While all labels appear in the …

Improve Gobra Package Information

---

src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala

As introduced in https://github.com/viperproject/silicon/pull/756

Add a flag to enable silicon's unsafe wildcard multiplication

---

src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/UnderlyingType.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/test/resources/regressions/features/arrays/array-length-simple2.gobra
src/test/resources/regressions/features/arrays/array-literal-simple1.gobra
src/test/resources/regressions/features/maps/maps-fail1.gobra
src/test/resources/regressions/features/maps/maps-simple1.gobra
src/test/resources/regressions/features/slices/slice-literal-simple1.gobra
src/test/resources/regressions/features/slices/slice-type-fail1.gobra
src/test/resources/regressions/issues/000129-2.gobra
src/test/scala/viper/gobra/typing/ExprTypingUnitTests.scala

Currently, the type system of Gobra disallows array literals like `[3]int{}` from occurring in strongly pure contexts, even though an array is a value type (similarly to structs). Furthermore, the type system (wrongly) allows slice and map literals in pure contexts, even though it shouldn't because slices and maps are reference types. This PR addresses this classification.
To implement this, I had to fix the function `underlyingTypeWithCtxP` to allow for ADTs

Fix purity classification of composite literals

---

src/main/antlr4/GobraParser.g4
src/main/java/viper/gobra/frontend/GobraParser.java
src/main/java/viper/gobra/frontend/GobraParserBaseVisitor.java
src/main/java/viper/gobra/frontend/GobraParserVisitor.java
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/ParseTreeTranslator.scala
src/main/scala/viper/gobra/frontend/info/base/Type.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/Implements.scala
src/main/scala/viper/gobra/frontend/info/implementation/property/TypeIdentity.scala
src/main/scala/viper/gobra/frontend/info/implementation/resolution/AdvancedMemberSet.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/TypeTyping.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/separation/GhostTyping.scala
src/main/scala/viper/gobra/translator/Names.scala
src/main/scala/viper/gobra/translator/encodings/structs/StructEncoding.scala
src/test/resources/regressions/features/ghost_field/ghost-embedding-fail01.gobra
src/test/resources/regressions/features/ghost_field/ghost-embedding-simple01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-comparison-simple01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-comparison-simple02.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-fail01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-ghost-type-fail01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-ghost-type-simple01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-interface-fail01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-interface-simple01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-map-fail01.gobra
src/test/resources/regressions/features/ghost_field/ghost-field-simple01.gobra
src/test/resources/regressions/features/wands/ghost-list.gobra
src/test/resources/regressions/issues/000420.gobra

This PR depends on PRs #747 & #755 and, thus, targets `ghost-field-target-branch`, which corresponds to the branch used in #755.
This PR adds ghost fields, i.e., allows the use of `ghost` in front of field declarations. Note that struct embeddings can (so far) not be ghost. While ghost fields work mostly analogously to actual, non-ghost, fields, there are a few restrictions / differences to point out:
- A struct with ghost fields cannot implement an interface, however, a pointer to such a struct can (see `ghost-field-interface-simple01.gobra` and `ghost-field-interface-fail01.gobra`)
- Actual equality (`==`) on structs considers only actual fields, i.e., structs are equal modulo ghost fields. To include ghost fields in the comparison, ghost equality (`===`) can be used instead (see …

Support for Ghost Fields

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/frontend/Config.scala

Extends banner to explain the 3 different modes for providing inputs to Gobra.
@reviewers: Please let me know whether this is (1) understandable and (2) sufficient.

Gobra CLI Input Documentation

---

src/main/scala/viper/gobra/Gobra.scala
src/main/scala/viper/gobra/frontend/Source.scala

Executing `Paths.get(filename).getParent` fails if `filename` is a relative path in the current folder (and thus does not have any path component besides the filename itself).
Please let me know if you have a great idea for a test case as we would need to invoke Gobra relative to a folder containing a Gobra file such that we can provide a path to the Gobra file without any path component.
Fixes #781

Fix issue #781

---

docs/tutorial.md

This PR makes sure the correct function is used in the example code of `docs/tutorial.md`.

docs: correct function name in tutorial

---

src/main/scala/viper/gobra/util/TypeBounds.scala
src/test/resources/regressions/features/overflow_checks/overflow_simple1.go

The current bounds specified for singed integer types are off. This PR fixes that.
The added test is rejected in the current state of Gobra, even though the program should definitely pass.
Reported by @gottschali

Fix bounds of singed integers for overflow checking

---

src/main/scala/viper/gobra/backend/ViperBackends.scala

For reasons to be discussed in the next viper meeting, it is desirable to keep the behavior of Gobra prior to PR https://github.com/viperproject/gobra/pull/812.
To that end, we had the option `--respectFunctionPrePermAmounts` to all of our backends

Use option `--respectFunctionPrePermAmounts` in the backends

---

src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/test/scala/viper/gobra/GobraTests.scala

Changes done in accordance to the corresponding change in Viper (https://github.com/viperproject/silver/pull/816).
The default is still Viper's old interpretation for fractional permissions because our case studies all use the old semantics, but we should switch in the future because the new interpretation leads to more concise specs.

Add support for new interpretation of fractional perms in pure function preconditions

---

src/main/scala/viper/gobra/backend/BackendVerifier.scala
src/main/scala/viper/gobra/backend/Carbon.scala
src/main/scala/viper/gobra/backend/ViperBackends.scala
src/main/scala/viper/gobra/frontend/Config.scala
src/test/resources/regressions/features/backends/carbon.gobra
src/test/resources/regressions/features/backends/silicon.gobra
src/test/resources/regressions/features/backends/vs-with-carbon.gobra
src/test/resources/regressions/features/backends/vs-with-silicon.gobra

Removes the `--disablePlugins` flag for ViperServer-based backends, fixes invalid command line options that are passed to Carbon (with and without ViperServer), and adds a simple testcase for each backed.
Adding testcases required changing `Config` and the way we merge in-file configuration options. In particular, I made `backend` optional such that we know while merging configuration options whether a backend has been specified or not. We emit a violation if one attempts to merge differing backends as the merge strategy is unclear in this case.
Closes #823

Fixes #823

---

genparser.sh
src/main/java/viper/gobra/frontend/GobraLexer.java
src/main/java/viper/gobra/frontend/GobraParser.java
src/main/java/viper/gobra/frontend/GobraParserBaseVisitor.java
src/main/java/viper/gobra/frontend/GobraParserVisitor.java

Adapts `genparser.sh` to turn absolute paths into relative ones in the generated parser files

Relative Paths in Generated Parser

---

src/main/scala/viper/gobra/reporting/DefaultErrorBackTranslator.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala
src/main/scala/viper/gobra/translator/transformers/TerminationDomainTransformer.scala
src/test/resources/regressions/issues/000828.gobra

This PR adds backtranslation of the (one and only) error that Viper's PredicateInstance plugin creates.
The reason is currently translated to `Permission to unknown might not suffice.` as positional information for the offending node is missing. However, this is fixed as soon [Silver PR #836](https://github.com/viperproject/silver/pull/836) got merged. I intentionally did not update the submodules and the fix introduced by this Silver PR can be propagated independently of this PR through our periodic submodule update mechansim.
Fixes #828

Fix issue 828

---

build.sbt

The relative path we are currently using in `build.sbt` does not work for projects that depend on Gobra, such as Gobra-IDE. Thus, this PR switches to using an absolute path.

Fix parser generation for dependers

---

src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/test/resources/regressions/features/slices/slice-cap-simple2.gobra

The following example fails to typecheck without an explicit typecast:
```
type IP []byte
requires len(x) <= cap(x)
decreases _
pure func foo(x IP) bool
```

Slice cap operation didn't check underlyingTypes

---

src/main/antlr4/GobraLexer.g4
src/main/scala/viper/gobra/frontend/InformativeErrorListener.scala
src/test/scala/viper/gobra/parsing/ParserUnitTests.scala

This PR addresses a bug discovered by @felixlinker where our parser just reports "no viable alternative at input '(proof'
func test(proof ProofType)" for the following input, thus, making it hard to spot that `proof` is a reserved word. While our parse error listener already supports pointing out reserved words, the list of reserved words was outdated. I hope to prevent similar bugs in the future by corresponding notes in `GobraLexer.g4`.
```
package main
func test(proof ProofType)
```

Fix reserved parser keyword error reporting

---

src/main/scala/viper/gobra/frontend/info/implementation/property/Implements.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/test/resources/regressions/features/domains/implements-interface-fail01.gobra
src/test/resources/regressions/features/domains/implements-interface-fail02.gobra
src/test/resources/regressions/features/domains/implements-interface-fail03.gobra
src/test/resources/regressions/features/domains/implements-interface-fail04.gobra
src/test/resources/regressions/features/domains/implements-interface-simple01.gobra
src/test/resources/regressions/features/domains/implements-interface-simple02.gobra

This PR allows domains to implement an interface (see `Implements.scala`).
A domain is identity preserving only if all types that show up as input or output parameters of domain functions of this domain are identity preserving.
PS: the motivation for this PR is that I want to implement a ghost interface for various types, one of them being a domain.

Domains under interface

---

src/main/scala/viper/gobra/frontend/info/implementation/property/Implements.scala
src/test/resources/regressions/features/domains/implements-interface-imported-simple01.gobra
src/test/resources/regressions/features/domains/implements-interface-imported-simple01/foo/foo.gobra

The added case to decide whether a domain is type identity preserving (see #860) causes a node not in tree exception when the domain is located in a different package. This PR fixes this bug.

Fix exception when checking whether an imported domain is identity preserving

---

src/main/resources/stubs/sync/waitgroup.gobra
src/test/resources/regressions/features/stubs/stubs3.gobra

Currently, we get an error when we import `sync` in a package that we try to verify with --noassumeInjectivityOnInhale:
```
Error at: <stubs/sync/waitgroup.gobra:24:10> Method contract is not well-formed. 
Quantified resource g might not be injective.
```
The fix is to split the array in the definition of WaitGroup to avoid generating the ill-formed qtfier at the encoding level. The actual choice of private fields does not matter and ideally, we would have been able to make this type completely opaque, but that is currently not possible in gobra

Fix error obtained when importing `sync` with flag --noassumeInjectivityOnInhale

---

.github/license-check/headers/Go.txt
src/main/resources/stubs/errors/errors.gobra

This PR extends the `errors` package to (finally!) provide the `New` function.

errors.New

---

src/main/antlr4/GobraParser.g4
src/main/scala/viper/gobra/ast/frontend/Ast.scala
src/main/scala/viper/gobra/ast/frontend/PrettyPrinter.scala
src/main/scala/viper/gobra/ast/internal/PrettyPrinter.scala
src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/Desugar.scala
src/main/scala/viper/gobra/frontend/ParseTreeTranslator.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/maps/MapEncoding.scala
src/main/scala/viper/gobra/translator/encodings/slices/SliceEncoding.scala
src/test/resources/regressions/features/maps/math-maps-simple1.gobra

In a recent conversation with @ThomasMayerl and @rayman2000, we realized that introducing ghost pure functions that convert from maps to dictionaries and from slices to sequences is still an unfortunate rite of passage for any user of Gobra. This PR addresses the former, which is impossible to fully implement as a pure function using the current syntax of Gobra, as we do not have a good way of iterating through maps without using loops. In addition, this conversion can be implemented super concisely and efficiently in Gobra already, due to the way maps are encoded.
I considered also implementing the conversion from slices to ghost collections, including seqs, sets and msets, but I don't have time atm

Add support for converting maps to dicts

---

src/main/scala/viper/gobra/reporting/BacktranslatingReporter.scala
src/main/scala/viper/gobra/reporting/VerifierError.scala

This PR introduces minor changes to Gobra's error reporting infrastructure to ensure compatibility with Silver plugins. Specifically, it updates the reporting pipeline to properly integrate with Silver's `PluginAwareReporter`. This ensures that all errors are passed through the configured plugins' error transformations before being reported, eliminating confusing error messages that occurred when using `refute` statements in Gobra.
To test functionality, you can verify this function:
```
package playground
func test() {
refute false
}
```
Gobra should produce the following output:
```
Verifying package .. - playground [14:19:01]
Gobra found 0 errors.
```
(Previously, it also printed an `Assertion failed` message originating from the `refute` statement.)
Conversely, verifying this code: …

Error reporting

---

src/main/scala/viper/gobra/translator/transformers/hyper/SIFLowGuardTransformer.scala
src/test/resources/regressions/issues/000883.gobra

This was clearly caused by a typo in the translation of `unfolding` expressions.

Fix issue 883

---

src/main/scala/viper/gobra/ast/internal/Program.scala
src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala
src/main/scala/viper/gobra/translator/encodings/StringEncoding.scala
src/test/resources/regressions/features/strings/strings-fail0.gobra
src/test/resources/regressions/features/strings/strings0.gobra
src/test/resources/regressions/issues/000831.gobra

This PR:
- Adds support for indexing strings (e.g., `"hello"[1]`)
- Relates the contents of a string `s` with the contents of a slice obtained with `[]byte(s)`. This fixes issue #831.
- Relates the contents of a slice `s` with the contents of the string `string(s)`. This **partially** addresses issue #832 (see my comment there).
At the moment, violating the precondition of an indexing operation (i.e., passing an invalid index to a string) leads to a bad error message, similar to `precondition of unknown may not hold`. This is similar to other parts of our encoding, where we are not able to generate good error messages when the precondition of a function internal to our encoding may not hold. PR https://github.com/viperproject/silver/pull/815 will hopefully allow us to fix that by …

Add support for indexing strings
